// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmicIntegrator.Data;

#nullable disable

namespace OmicIntegrator.Migrations
{
    [DbContext(typeof(BaseCtx))]
    partial class BaseCtxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GenomeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenomeId");

                    b.ToTable("Datasets");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Proteomes.Peptide", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DatasetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdInDataSet")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sequence")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("ProteomesPeptides");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Proteomes.PeptideFeature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PeptideId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("PeptideId");

                    b.ToTable("ProteomesPeptidesFeatures");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Proteomes.PeptideModification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModificationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PeptideId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResiduePosition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeptideId");

                    b.ToTable("ProteomesPeptidesModifications");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Proteomes.ProteomeValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Intensity")
                        .HasColumnType("TEXT");

                    b.Property<long>("PeptideId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SampleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeptideId");

                    b.HasIndex("SampleId");

                    b.ToTable("ProteomesValues");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("IntensityThreshold")
                        .HasColumnType("TEXT");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Transcriptomes.RnaValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SampleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tpm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("SampleId");

                    b.ToTable("RnaValues");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DatasetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Feature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long>("End")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGeneRepresentative")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<long>("Start")
                        .HasColumnType("INTEGER");

                    b.Property<char?>("Strand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("SequenceId");

                    b.HasIndex("Start");

                    b.HasIndex("Type");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("OmicIntegrator.Data.FeatureGoTerm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GoTermId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("GoTermId");

                    b.HasIndex("Source");

                    b.ToTable("FeaturesGoTerms");
                });

            modelBuilder.Entity("OmicIntegrator.Data.FeatureMotif", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("End")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MotifId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PValue")
                        .HasColumnType("REAL");

                    b.Property<int>("Start")
                        .HasColumnType("INTEGER");

                    b.Property<char>("Strand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue('+');

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("MotifId");

                    b.HasIndex("PValue");

                    b.ToTable("FeaturesMotifs");
                });

            modelBuilder.Entity("OmicIntegrator.Data.FeatureParent", b =>
                {
                    b.Property<long>("FeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FeatureId", "ParentId");

                    b.HasIndex("ParentId");

                    b.ToTable("FeaturesParents");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Genome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genomes");
                });

            modelBuilder.Entity("OmicIntegrator.Data.GoTerm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GoTerms");
                });

            modelBuilder.Entity("OmicIntegrator.Data.GoTermsRelationship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferredId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("ReferredId");

                    b.HasIndex("Relationship");

                    b.ToTable("GoTermsRelactinships");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Motif", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalSpecies")
                        .HasColumnType("TEXT");

                    b.Property<string>("Program")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sequence")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Program", "Code")
                        .IsUnique();

                    b.ToTable("Motifs");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Sequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("GenomeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsChromosome")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long>("Start")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenomeId");

                    b.ToTable("Sequences");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Standardization.SampleTypeValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HighAbundance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Presence")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SAValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SValue_SD")
                        .HasColumnType("TEXT");

                    b.Property<int>("SampleType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StandardizationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("StandardizationId");

                    b.ToTable("SA_SampleTypeValues");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Standardization.SummarizedPhosphosite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExclusivePeptides")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<char>("Residue")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResiduePosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StandardizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("StandardizationId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("SummarizedPhosphosites");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Standardization.TreatmentValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("StandardizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("WithExclusivity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("StandardizationId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("S_TreatmentValues");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Standardization.TreatmentsStandardization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenomeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TreatmentsStandardizations");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Dataset", b =>
                {
                    b.HasOne("OmicIntegrator.Data.Genome", "Genome")
                        .WithMany()
                        .HasForeignKey("GenomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genome");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Proteomes.Peptide", b =>
                {
                    b.HasOne("OmicIntegrator.Data.Datasets.Dataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Proteomes.PeptideFeature", b =>
                {
                    b.HasOne("OmicIntegrator.Data.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmicIntegrator.Data.Datasets.Proteomes.Peptide", "Peptide")
                        .WithMany()
                        .HasForeignKey("PeptideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Peptide");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Proteomes.PeptideModification", b =>
                {
                    b.HasOne("OmicIntegrator.Data.Datasets.Proteomes.Peptide", "Peptide")
                        .WithMany("Modifications")
                        .HasForeignKey("PeptideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peptide");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Proteomes.ProteomeValue", b =>
                {
                    b.HasOne("OmicIntegrator.Data.Datasets.Proteomes.Peptide", "Peptide")
                        .WithMany()
                        .HasForeignKey("PeptideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmicIntegrator.Data.Datasets.Sample", "Sample")
                        .WithMany("ProteomeValues")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peptide");

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Sample", b =>
                {
                    b.HasOne("OmicIntegrator.Data.Datasets.Treatment", "Treatment")
                        .WithMany("Samples")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Transcriptomes.RnaValue", b =>
                {
                    b.HasOne("OmicIntegrator.Data.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmicIntegrator.Data.Datasets.Sample", "Sample")
                        .WithMany("RnaValues")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Treatment", b =>
                {
                    b.HasOne("OmicIntegrator.Data.Datasets.Dataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Feature", b =>
                {
                    b.HasOne("OmicIntegrator.Data.Sequence", "Sequence")
                        .WithMany()
                        .HasForeignKey("SequenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sequence");
                });

            modelBuilder.Entity("OmicIntegrator.Data.FeatureGoTerm", b =>
                {
                    b.HasOne("OmicIntegrator.Data.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmicIntegrator.Data.GoTerm", "GoTerm")
                        .WithMany()
                        .HasForeignKey("GoTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("GoTerm");
                });

            modelBuilder.Entity("OmicIntegrator.Data.FeatureMotif", b =>
                {
                    b.HasOne("OmicIntegrator.Data.Feature", "Feature")
                        .WithMany("MotifMatches")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmicIntegrator.Data.Motif", "Motif")
                        .WithMany()
                        .HasForeignKey("MotifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Motif");
                });

            modelBuilder.Entity("OmicIntegrator.Data.FeatureParent", b =>
                {
                    b.HasOne("OmicIntegrator.Data.Feature", "Feature")
                        .WithMany("ParentsFP")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmicIntegrator.Data.Feature", "Parent")
                        .WithMany("FeaturesFP")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OmicIntegrator.Data.GoTermsRelationship", b =>
                {
                    b.HasOne("OmicIntegrator.Data.GoTerm", "Reference")
                        .WithMany("Referred")
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmicIntegrator.Data.GoTerm", "Referred")
                        .WithMany("References")
                        .HasForeignKey("ReferredId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reference");

                    b.Navigation("Referred");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Sequence", b =>
                {
                    b.HasOne("OmicIntegrator.Data.Genome", "Genome")
                        .WithMany("Sequences")
                        .HasForeignKey("GenomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genome");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Standardization.SampleTypeValue", b =>
                {
                    b.HasOne("OmicIntegrator.Data.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmicIntegrator.Data.Standardization.TreatmentsStandardization", "Standardization")
                        .WithMany("SAValues")
                        .HasForeignKey("StandardizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Standardization");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Standardization.SummarizedPhosphosite", b =>
                {
                    b.HasOne("OmicIntegrator.Data.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmicIntegrator.Data.Standardization.TreatmentsStandardization", "Standardization")
                        .WithMany()
                        .HasForeignKey("StandardizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmicIntegrator.Data.Datasets.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Standardization");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Standardization.TreatmentValue", b =>
                {
                    b.HasOne("OmicIntegrator.Data.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmicIntegrator.Data.Standardization.TreatmentsStandardization", "Standardization")
                        .WithMany("SValues")
                        .HasForeignKey("StandardizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmicIntegrator.Data.Datasets.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Standardization");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Proteomes.Peptide", b =>
                {
                    b.Navigation("Modifications");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Sample", b =>
                {
                    b.Navigation("ProteomeValues");

                    b.Navigation("RnaValues");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Datasets.Treatment", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Feature", b =>
                {
                    b.Navigation("FeaturesFP");

                    b.Navigation("MotifMatches");

                    b.Navigation("ParentsFP");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Genome", b =>
                {
                    b.Navigation("Sequences");
                });

            modelBuilder.Entity("OmicIntegrator.Data.GoTerm", b =>
                {
                    b.Navigation("References");

                    b.Navigation("Referred");
                });

            modelBuilder.Entity("OmicIntegrator.Data.Standardization.TreatmentsStandardization", b =>
                {
                    b.Navigation("SAValues");

                    b.Navigation("SValues");
                });
#pragma warning restore 612, 618
        }
    }
}
